---
services:
  bitwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      WEBSOCKER_ENABLED: "true"
    volumes:
      - ${DATA_DIR}:/data
  caddy:
    image: caddy:2.11.4
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      DOMAIN: ${DOMAIN}
      LOG_FILE: "/data/access.log"
